### PR TITLE
license header updated

### LINKED ISSUE #58: Licence Header is outdated
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02/#copyright-and-license-header

https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/52341eeb3d9a7e86ec0dcdfcf0c970c02336d385/backend/pom.xml#L3

https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/fdf93a6abcb709571f75286c57380bbb9fa73b78/pom.xml#L3

### PR DESCRIPTION
**Pull request by bs-sili**
## Description
The license headers have been updated.

fixes #58

### CODE REVIEW

**Comment by FaGru3n** [comment]
i would mark the year-numbers with a `YYYY,YYYY` instead of  `YYYY-YYYY` see example
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02#copyright-and-license-header

**Review by FaGru3n — CHANGES_REQUESTED** [review]
i would mark the year-numbers with a YYYY,YYYY instead of YYYY-YYYY see example
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02#copyright-and-license-header

**Review by FaGru3n — APPROVED** [review]
LGTM thanks

**Comment by FaGru3n** [comment]
@bs-sili are you already a committer or should i merge it?

**Comment by shijinrajbosch** [comment]
LGTM

**Comment by FaGru3n** [comment]
Is anyone from your team a committer who can merge?

**Comment by bs-sili** [comment]
Yes, we have committers. At the moment they are out of office but within the next hour they will be there. :-)

**Pull request merged**
